acme_users_homepage:
    path:     /
    defaults: { _controller: AcmeUsersBundle:Default:index }
acme_users_create:
    path:     /acme/users/create
    defaults: { _controller: AcmeUsersBundle:Default:create }
acme_users_register:
    path:     /acme/users/register
    defaults: { _controller: AcmeUsersBundle:Default:register }
acme_users_create2:
    path:     /acme/users/create2
    defaults: { _controller: AcmeUsersBundle:Default:create2 }
acme_users_show:
    path:     /acme/users/show
    defaults: { _controller: AcmeUsersBundle:Default:show }
acme_users_edit:
    path:     /acme/users/edit
    defaults: { _controller: AcmeUsersBundle:Default:edit }