acme_users_homepage:
    path:     /
    defaults: { _controller: AcmeUsersBundle:Index:index }
acme_users_create:
    path:     /users/create
    defaults: { _controller: AcmeUsersBundle:Index:create }
acme_users_register:
    path:     /users/register
    defaults: { _controller: AcmeUsersBundle:Register:register }
acme_users_show:
    path:     /users/show/{page}
    defaults: { _controller: AcmeUsersBundle:Index:show, page: 1 }
acme_users_edit:
    path:     /users/edit/{id}
    defaults: { _controller: AcmeUsersBundle:Index:edit }
    methods:  [GET, POST]
acme_users_delete:
    path:     /users/delete/{id}
    defaults: { _controller: AcmeUsersBundle:Index:delete }
    methods:  [GET]
acme_users_login:
    path:     /login
    defaults: { _controller: AcmeUsersBundle:Security:login }
acme_users_login_check:
    path:     /login_check
    defaults: { _controller: AcmeUsersBundle:Security:loginCheck }
logout:
    path: /logout