<?php

namespace Acme\UsersBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{
    /**
     *  get all users ordered by name
     * @return mixed
     */
    public function findAllOrderedByName()
    {
        return $this->createQueryBuilder()
            ->sort('name', 'ASC')
            ->getQuery()
            ->execute();
    }
    
    
    public function getFirstUser()
    {
        return $this->createQueryBuilder()
            ->field('name')->equals('user1')
            ->getQuery()
            ->getSingleResult();
    }
}