Acme\UsersBundle\Document\User:
    repositoryClass: Acme\UsersBundle\Repository\UserRepository
    fields:
        id:
            id:  true
        name:
            type: string
        password:
            type: string
    properties:
        name:
            - NotBlank: ~
        password:
            - NotBlank: ~
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    type: document
    referenceMany:
        groups:
          targetDocument: \Acme\UsersBundle\Document\Group
    