Acme\UsersBundle\Document\User:
    repositoryClass: Acme\UsersBundle\Repository\UserRepository
    fields:
        id:
            id:  true
        name:
            type: string
        password:
            type: string